### PR TITLE
[snowplow-analytics] ✨ Add session context

### LINKED ISSUE #18: Add session tracking
### Description

We can add AMP session tracking attributes to our collection. 

### Proposal
Add a new schema describing the AMP session and the available identifiers we can track.

The description and naming on the attributes available is as such from the [amp repository (https://github.com/ampproject/amphtml/issues/33990):

- Session_id: a low entropy value persisted for 30 minutes per domain per vendor
- Session Creation Timestamp: a timestamp is seconds since epoch when the current session started
- Session Count: starts at 1 and is incremented each time a new session starts
- Engaged: 0 if there has not yet been user engagement and 1 once user engagement is achieved (signaling that this is not a bounced session)
- last-event-timestamp: a timestamp in seconds since epoch when the most recent event was generated

From the above, the naming we chose to go about is:
- `ampSessionId` → Session_id
- `ampSessionIndex` → Session Count
- `sessionEngaged` → Engaged
- `lastSessionEventTimestamp` → last-event-timestamp
- `sessionCreationTimestamp` → Session Creation Timestamp

These would be implemented in a new context which would be carried over with every event, as we already do with ones like amp_id.

### PR DESCRIPTION
**Pull request by igneel64**
### Description

Add a new schema describing the AMP session and the available identifiers we can track.

The description and naming on the attributes available is as such from the [amp repository](https://github.com/ampproject/amphtml/issues/33990):

- Session_id: a low entropy value persisted for 30 minutes per domain per vendor
- Session Creation Timestamp: a timestamp is seconds since epoch when the current session started
- Session Count: starts at 1 and is incremented each time a new session starts
- Engaged: 0 if there has not yet been user engagement and 1 once user engagement is achieved (signaling that this is not a bounced session)
- last-event-timestamp: a timestamp in seconds since epoch when the most recent event was generated

From the above, the naming we chose to go about is:
- `ampSessionId` → Session_id
- `ampSessionIndex` → Session Count
- `sessionEngaged` → Engaged
- `lastSessionEventTimestamp` → last-event-timestamp
- `sessionCreationTimestamp` → Session Creation Timestamp

These are implemented in a new context which would be carried over with every event, as we already do with ones like amp_id.

closes #18  

Pending schema `iglu:dev.amp.snowplow/amp_session/jsonschema/1-0-0`

### CODE REVIEW

**Review by matus-tomlein — APPROVED** [review]
LGTM!

FYI: I think the `lastSessionEventTimestamp` property in the schema should also have `null` as an accepted type as it is not a required property.

**Review by AlexBenny — COMMENTED** [review]
Great, thanks for bringing this forward!
It looks good to me. Can we add examples and tests as in the [old PR](https://github.com/snowplow-incubator/amphtml/pull/15/files) Colm did?
I wonder if the AMP tests can be good to test the session. AMP stuff confuses me!

About the schema, I agree with Matus that the `lastSessionEventTimestamp` should have the null option in the type if optional. In theory it shouldn't be mandatory but in recent times it has been enforced for all the schemas submitted to Iglu.

**Comment by colmsnowplow** [comment]
I gave this a quick test in review of schema PR - looks good.

It doesn't look like we update `trackerVersion`, which corresponds to `v_tracker`. I think it's a good idea to do so as it would help anyone debugging a historical issue. :)

**Comment by igneel64** [comment]
https://github.com/ampproject/amphtml/pull/38533

**Comment by igneel64** [comment]
Completed and released

**Pull request closed without merging**
